// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For Turso: set DATABASE_URL=libsql://... and TURSO_AUTH_TOKEN=...
    // For local: set DATABASE_URL=file:./dev.db (no auth token needed)
    url: process.env["DATABASE_URL"],
    ...(process.env["TURSO_AUTH_TOKEN"]
      ? { authToken: process.env["TURSO_AUTH_TOKEN"] }
      : {}),
  },
});
